### ISSUE TITLE
Las rendezvous que ya hay en el populate no estan bien ( o puede que sea el método que las devuelve)

### ISSUE THREAD

**Issue by JJCCGGRR24** [JJCCGGRR24/Design-and-Testing#16]
Por ejemplo el user con id 72 (El llamado Chioma) si yo estando sin autenticar me voy a mirar sus rendezvous solo aparecen dos, cuando deberían aparecer tres, el fallo es que en el populate no se están metiendo las rendezvous que crea en la tabla de creadas y las de asistidas, solo en las creadas con lo que esa no la toma como que va a asistir y por eso no la muestra.

**Comment by Escrabel** [comment]
Efectivamente, el error es del populate, que lo hice sin tener en cuenta eso

**Comment by Escrabel** [comment]
Arreglado
