### ISSUE TITLE
Los rendezvous eliminados (no de la database) deberían mostrarse con un flags de que han sido eliminados

### ISSUE THREAD

**Issue by JJCCGGRR24** [JJCCGGRR24/Design-and-Testing#19]
Deleted rendezvouses are flagged as such when they are displayed.
No especifica mucho pero yo diría que los mostraramos al mismo user las que el mismo borro, que eso sea 
transparente para el usuario cliente

**Comment by fraagucan2** [comment]
Lo hemos debatido hoy y aunque lo marques como borrado puede verlo todo el mundo pero debe de aparecer en algun lado que esta marcado como borrado @JJCCGGRR24 @jullopjim1 @Escrabel

**Comment by Escrabel** [comment]
Procedo a marcarlas de color rojo

**Comment by Escrabel** [comment]
Y añadida columna además

**Comment by Escrabel** [comment]
Y añadida columna deleted
