### ISSUE TITLE
Fallo al enviar el formulario vacío en el create de rendezvous

### ISSUE THREAD

**Issue by fraagucan2** [JJCCGGRR24/Design-and-Testing#23]
al enviar el formulario vacío en la url http://localhost:8080/Acme-Rendezvous/rendezvous/user/create.do 
![sin titulo](https://user-images.githubusercontent.com/22836642/36741052-67bd23aa-1be4-11e8-9b3f-52962955487f.png)

**Comment by Escrabel** [comment]
![image](https://user-images.githubusercontent.com/18685581/36741725-247d7a0c-1be6-11e8-9af4-d10bc1a9b8e9.png)
Arreglado

**Comment by fraagucan2** [comment]
cambia en español null por vacía @Escrabel

**Comment by Escrabel** [comment]
no puedo es el mensaje por defecto del @NOTNULL, si lo cambio ahí se cambia en todos lados
