### ISSUE TITLE
Fallo al ver citas de un usuario

### ISSUE THREAD

**Issue by fraagucan2** [JJCCGGRR24/Design-and-Testing#24]
Sin estar logueado entro en la pantalla users y le doy a ver las rendezvous de un usuario.
Segun el requisito 4.2 deberia de estar permitido pero al pinchar aparece el siguiente error.
URL: http://localhost:8080/Acme-Rendezvous/rendezvous/user/list.do?userId=75

![sin titulo](https://user-images.githubusercontent.com/22836642/36741581-c91571d8-1be5-11e8-9419-9842208c03b5.png)

**Comment by Escrabel** [comment]
![image](https://user-images.githubusercontent.com/18685581/36743697-2c89ed3e-1beb-11e8-94e5-68d0d59ac2f8.png)
Arreglao
