### ISSUE TITLE
Aparece el boton de editar cuando un rendezvous esta borrado

### ISSUE THREAD

**Issue by fraagucan2** [JJCCGGRR24/Design-and-Testing#25]
He borrado un rendezvous y sigue apareciendo el boton de editar, cosa que no deberia.

![sin titulo](https://user-images.githubusercontent.com/22836642/36741988-d615cd0a-1be6-11e8-99cb-ca8c1ff01980.png)

**Comment by Escrabel** [comment]
Arreglado

![image](https://user-images.githubusercontent.com/18685581/36744570-78e35b78-1bed-11e8-83a0-d0413ee41f80.png)
