### ISSUE TITLE
La imagen en el comentario no debe ser obligatoria

### ISSUE THREAD

**Issue by fraagucan2** [JJCCGGRR24/Design-and-Testing#26]
Al añadir un comentario me obliga a añadir un enlace de foto pero segun los requisitos es opcional.

3. The system must handle comments about the rendezvouses. For every comment the system must store the user who wrote it, the moment when it was written, the corresponding text, and an optional picture that is referenced by means of a URL.

![sin titulo](https://user-images.githubusercontent.com/22836642/36742765-cb6067b0-1be8-11e8-9726-a1d0617544d5.png)

**Comment by Escrabel** [comment]
Arreglao

![image](https://user-images.githubusercontent.com/18685581/36744201-7c62cce4-1bec-11e8-9501-99ade7c5369e.png)
