### ISSUE TITLE
Boton de cancelar erroneo en la vista de edit de comentario

### ISSUE THREAD

**Issue by fraagucan2** [JJCCGGRR24/Design-and-Testing#28]
En la URL http://localhost:8080/Acme-Rendezvous/announcement/user/create.do?rendezvousId=77 al pulsar en el boton cancelar nos aparece el siguiente error:

![sin titulo](https://user-images.githubusercontent.com/22836642/36745417-b01b0ec2-1bef-11e8-97eb-d8ddff1c8c08.png)

**Comment by Escrabel** [comment]
Arreglao
