### ISSUE TITLE
Phone debe poder ser nulo

### ISSUE THREAD

**Issue by fraagucan2** [JJCCGGRR24/Design-and-Testing#4]
1.The  system  must  support  two kindsof  actors,  namely:  administrators  and  users. It  must store  the following  information  regarding  them:  their  names,  surnames,  postal  addresses (optional), phone numbers (optional), and email addresses. 

El numero de telefono es opcional y al registrarme no puedo dejar el phone vacío. Hay que cambiar el dominio (Actor) y el objeto formulario (RegisterForm).

**Comment by fraagucan2** [comment]
Da el siguiente error: "Does not match pattern"

**Comment by ordomedina** [comment]
He quitado el pattern de phone tanto en RegisterForm como en Actor ya que el enunciado no pide ningún tipo de patrón
