### ISSUE TITLE
Cambiar la forma de borrar un rendezvous

### ISSUE THREAD

**Issue by fraagucan2** [JJCCGGRR24/Design-and-Testing#6]
Actualmente incluso al crear un rendezvous te aparece un campo "¿Quisiera borrar esta cita?:" en el que eliges si deseas borrarla. 

Lo ideal sería a traves del tipico boton de borrar.

**Comment by fraagucan2** [comment]
Esconder ese campo si se esta creando el rendezvous

**Comment by jullopjim1** [comment]
Esto lo cambio en breves
